[server]
files_root="server_files"
password="TrueMathNote1!*"
ignored_paths=[
	""
]

[client]
server_url="https://skywriter.ejrobotics.com"

[client.mappings.files]
"/home/jt/sudoku.py"="/sudoku.py"

[client.mappings.dirs]
"/home/jt/dotfiles/"="/dotfiles/"
