[server]
file_root="files"

[client]
server_url="http://localhost:8000"
sync_seconds=10

[client.mappings.files]
"test.txt"="/test.txt"
"duality.jpg"="/images/duality.jpg"

[client.mappings.directories]
"some/dir/"="/another/dir/"
